service: hapi-lambda-demo
provider:
  name: aws
  runtime: nodejs8.10

stage: dev
region: us-east-1

functions:
  api:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
